version: '3'

services:
  
  easy-food-api:
    image: acme/easy-food-api:latest
    container_name: easy-food-api
    build:
      context: ../../
      dockerfile: ./src/Presentation/EF.Api/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:80
    ports:
      - "8080:80"
    depends_on:
      - easy-food-db
  
  easy-food-db:
    image: postgres:latest
    container_name: easy-food-db
    environment:
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme
      POSTGRES_DB: easy-food
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  pgdata: