// <auto-generated />
using System;
using EF.Pagamentos.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EF.Pagamentos.Infra.Migrations
{
    [DbContext(typeof(PagamentoDbContext))]
    [Migration("20231228224453_BaseInicialPagamentos")]
    partial class BaseInicialPagamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EF.Pagamentos.Domain.Models.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoFormaPagamento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoFormaPagamento")
                        .IsUnique();

                    b.ToTable("FormasPagamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a68e2ed-8e67-4f10-8ab5-fa7c67bf6371"),
                            Descricao = "Cartão de Crédito",
                            TipoFormaPagamento = 0
                        },
                        new
                        {
                            Id = new Guid("17b6f2bc-520d-48e7-9008-2723fe5d2bcb"),
                            Descricao = "Pix",
                            TipoFormaPagamento = 1
                        },
                        new
                        {
                            Id = new Guid("29daa6de-862c-495f-93bf-153fd7d58dc0"),
                            Descricao = "Mercado Pago",
                            TipoFormaPagamento = 2
                        });
                });

            modelBuilder.Entity("EF.Pagamentos.Domain.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("EF.Pagamentos.Domain.Models.Pagamento", b =>
                {
                    b.HasOne("EF.Pagamentos.Domain.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .IsRequired();

                    b.Navigation("FormaPagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
