POST {{baseUrl}}/api/identidade
Content-Type: application/json

{
  "nome": "José",
  "sobrenome": "Castilho",
  "cpf": "020.356.151-49",
  "email": "jose1984r@mail.com.br",
  "senha": "C58t(QPxgQ",
  "senhaConfirmacao": "C58t(QPxgQ"
}

###

POST {{baseUrl}}/api/identidade/autenticar
Content-Type: application/json

{
  "email": "renato_gabriel_castro@deze7.com.br",
  "senha": "C58t(QPxgQ"
}

###

POST {{baseUrl}}/api/identidade/acessar-sem-identificacao
Content-Type: application/json

###

POST {{baseUrl}}/api/identidade/acessar-sem-identificacao?cpf=160.779.510-80
Content-Type: application/json