kind: PersistentVolume
apiVersion: v1
metadata:
  name: easy-food-db-pv-volume
  labels:
    app: easy-food-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"