kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: easy-food-db-pv-claim
  labels:
    app: easy-food-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi