kind: Service
apiVersion: v1
metadata:
  name: easy-food-db
  labels:
    app: easy-food-db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
  selector: 
    app: easy-food-db