kind: Secret
apiVersion: v1
metadata:
  name: easy-food-api-secrets
data:
  appsettings.json: |
    ewogICJMb2dnaW5nIjogewogICAgIkxvZ0xldmVsIjogewogICAgICAiRGVmYXVsdCI6ICJJbmZvcm1hdGlvbiIsCiAgICAgICJNaWNyb3NvZnQuQXNwTmV0Q29yZSI6ICJXYXJuaW5nIgogICAgfQogIH0sCiAgIkFsbG93ZWRIb3N0cyI6ICIqIiwKICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7CiAgICAiRGVmYXVsdENvbm5lY3Rpb24iOiAiSG9zdD1sb2NhbGhvc3Q7UG9ydD01NDMyO0RhdGFiYXNlPWVhc3ktZm9vZDtVc2VybmFtZT1hY21lO1Bhc3N3b3JkPWFjbWUiCiAgfSwKICAiSWRlbnRpZGFkZVNldHRpbmdzIjogewogICAgIlNlY3JldCI6ICJFMDc2Qjc1MS04OEFDLTQzNDQtQTkzMS04OEFCRkQ2NjU5MTYiLAogICAgIkV4cGlyYXRpb25Ib3VycyI6IDIsCiAgICAiSXNzdWVyIjogIkVhc3lGb29kIiwKICAgICJWYWxpZEluIjogImxvY2FsaG9zdDo1MDAyIgogIH0KfQo=